### PR TITLE
Fix wPOKT decimals

### PR DESCRIPTION
**Pull request by crisog**
We were using 18 decimals for wPOKT, but it wPOKT is going to be a 6 decimals token. So we need to update the app accordingly.

Additionally, this PR fixes a small problem with`globalStakingSharesSec` being obtained at a certain timestamp, and I was calculating ownership share based on the current timestamp (wrong since it should be the last time the subgraph was updated). This error caused ownership share to be slightly above 100%.

Also, `Total Yield Earned` had a wrong formula which was fixed in this PR too.

### CODE REVIEW

**Comment by Evalir** [comment]
This looks _preliminary_ good—have we done this to make sure this is all:
- [x] Search (and replace is needed) of `18` for `6`?
- [x] Replaced _all_ contract interactions for `6` decimals?
- [x] Replaced _all_ token displays that rely on `18` decimals being implicit for `6` decimals?

After we do this, let's put some screenshots/GIFs of the app showing proper balances with their on-chain counterparts.

**Review by ECWireless — APPROVED** [review]
All these commits look good to me. I'm going to make my own pass through the entire codebase later today. But if I catch anything, I'll just make a new PR.

**Comment by ECWireless** [comment]
> All these commits look good to me. I'm going to make my own pass through the entire codebase later today. But if I catch anything, I'll just make a new PR.

jk, just went thru the whole codebase now with search and replace, and all looks good.

**Comment by Evalir** [comment]
@crisog lemme know when you want a review so we can merge this ASAP!

**Review by Evalir — APPROVED** [review]
Yup, looks good!

**Pull request merged**
